# theme: jekyll-theme-modernist
theme: jekyll-theme-slate
title: "Deterministic Workflows"
description: "A collaboration between UPenn & Indiana University."
github:
  is_project_page: false
  is_user_page: false
  repository_url: https://github.com/iu-parfunc/detbox-project
