# theme: jekyll-theme-modernist
theme: jekyll-theme-hacker
title: "Deterministic Workflows Project"
github:
  is_project_page: false
  is_user_page: false
  repository_url: https://github.com/iu-parfunc/detbox-project
  project_title: "Deterministic Workflows Project"
  project_tagline: "TEST TEXT"
