theme: jekyll-theme-modernist
title: "Deterministic Workflows Project"
github:
  is_project_page: true
  is_user_page: false
  repository_url: https://github.com/iu-parfunc/detbox-project
  project_title: "Deterministic Workflows Project"
